### ISSUE TITLE
compatibility with openwrt

### ISSUE THREAD

**Issue by ringo458** [misje/dhcpoptinj#11]
I'm new sorry if this is inappropriate. I am requesting that this tool be incorporated as a package in openwrt, or perhaps a suggestion about how to install the source into the toolkit and make automatically.

thanks

**Comment by misje** [comment]
I will look into it. It looks like people have made utilities that resembles dpkg-buildpackage, which would be great. I will first update the deb scripts and then see what I have to do to make it work with opkg.

**Comment by misje** [comment]
How would the program be run in openwrt? And if it will be run as a daemon, how will it be configured? I have looked into UCI/luci, but I haven't found good material explaining how a package can provide settings accessible from the web interface. Have you got any ideas?

**Comment by ringo458** [comment]
Hi Andreas,

I left this problem behind some time ago. What wound up happening was I 
did get openwrt running on a gli
box with some kind of ad blocking but it was a little unstable. Then I 
solved various issues that I had with
A raspberry pi and some complex dns daemon that I can't remember off the 
top of my head. It seems like I was
done with this set of problems months ago. Thanks for your interest 
though. I do sort of remember that DHCP
injection was not the tool that I wound up using.

------ Original Message ------
