### ISSUE TITLE
Nftables support

### ISSUE THREAD

**Issue by Harvie** [misje/dhcpoptinj#20]
Hi! Can you please add support for nftables based firewalls? I can't longer use (now deprecated) iptables in my setup...

**Comment by misje** [comment]
Does nftables not work? As far as I can tell, netfilter-queue works just as well using nftables. I haven't tried, however.

[Here](https://wiki.nftables.org/wiki-nftables/index.php/Queueing_to_userspace) is hopefully a helpful note on the nftables wiki. Let me know what prevents you from using dhcpoptinj with nftables. And if you have example lines using nftables that I can publish, that'd be great!
