### ISSUE TITLE
Enhancement - bypassing for certain mac addresses 

### ISSUE THREAD

**Issue by DRTEK** [misje/dhcpoptinj#6]
Can we add a key for bypassing this function  certain mac addresses ?
thanks

**Comment by misje** [comment]
What you want is to adjust your iptables rule(s). You can do all the filtering you want in iptables that doesn't depend on the BOOTP/DHCP payload. For MAC addresses use something like `-m mac --mac-source`.

There is a MAC address in the BootP::clientHwAddr field, but unless your requests are forwarded, you should be able to filter by the source MAC address in the link layer.
