### ISSUE TITLE
lib didn't work

### ISSUE THREAD

**Issue by VolunPotest** [misje/dhcpoptinj#8]
Hi!
Program works, but Wireshark didn't see edited package - only old version of the package.
I use virtualbox and NAT inteface eth0.
When i try use dhclient - dhcpoptinj see  that packet -  but tcpdump dont have additional option.
What i can do ?
tnx

**Comment by misje** [comment]
Can you please start by providing 
- the command line showing how you are running dhcpoptinj
- the relevant iptables rule(s) used together with dhcpoptinj
- what your network setup is, what you are trying to achieve and what you expect to see

**Comment by misje** [comment]
No feedback received.
