### ISSUE TITLE
Does this work on a DHCP server?

### ISSUE THREAD

**Issue by chongpohkit** [misje/dhcpoptinj#9]
Hi,

Not really an issue, but don't see where I could email you. 

Wanted to ask if this would work on a DHCP server? I think that DHCPD receives DHCP requests on a raw socket and bypasses netfilter completely.

Thanks.

**Comment by misje** [comment]
This is an interesting question. I did a little bit of research, and the answer seems to be no. dhcpd uses raw sockets and bypasses the TCP/IP stack. My understanding is that the netfilter hooks (and iptables) reside in the TCP/IP stack, so mangling dhcpd's network traffic will therefore not be possible. However, I may be wrong!
